# Rename this file to languages.toml to enable multilingual support
[ko]
languageName = "한국어"
languageDirection = "ltr"
title = "VFX & Technical Artist Figix"
weight = 1

[en]
languageName = "English"
languageDirection = "ltr"
title = "VFX & Technical Artist Figix"
weight = 2
